AWSTemplateFormatVersion: 2010-09-09
Description: >-
  emails-queue-api

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String
    Description: AWS account ID
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      certificate: adce1a21-90b4-4120-8548-111215e582f0
      domain: sms-queue-api.dbowland.com
      queue: sms-queue-service-SimpleQueue-MTYuJ185qzAl.fifo
      zoneId: Z072422417XWM8PIXXSFA
    test:
      certificate: 6a48cba7-feb9-4de5-8cbf-d383140fcdef
      domain: sms-queue-api.bowland.link
      queue: sms-queue-service-test-SimpleQueue-zO4CTBnv6cwy.fifo
      zoneId: Z01312547RGU1BYKIJXY

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for sms-queue-api
      Domain:
        DomainName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
        CertificateArn: !Sub
          - 'arn:aws:acm:us-east-1:${AccountId}:certificate/${Certificate}'
          - Certificate: !FindInMap [EnvironmentMap, !Ref Environment, certificate]
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !FindInMap [EnvironmentMap, !Ref Environment, zoneId]
        BasePath:
          - /v1

  PostItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/post-item.postItem
      CodeUri: './dist'
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Description: Adds sms messages to the queue to be sent.
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Grant access to SQS queue
        - SQSSendMessagePolicy:
            QueueName: !FindInMap [EnvironmentMap, !Ref Environment, queue]
      Environment:
        Variables:
          SQS_MESSAGE_QUEUE_ID: sms
          SQS_QUEUE_URL: !Sub
            - 'https://sqs.us-east-1.amazonaws.com/${AccountId}/${Queue}'
            - Queue: !FindInMap [EnvironmentMap, !Ref Environment, queue]
      Events:
        ApiKey:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /messages
            Method: post
            Auth:
              ApiKeyRequired: true

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [PostItemFunction]
    Properties:
      LogGroupName: !Sub /aws/lambda/${PostItemFunction}
      RetentionInDays: 30
